#ifndef RECEIPTSELECTIONBUTTON_H
#define RECEIPTSELECTIONBUTTON_H

#include <QWidget>

namespace Ui {
/**
 * @brief UI class for OrderSelectionButton.
 *
 * This class is generated by Qt Designer and contains the UI components for the
 * OrderSelectionButton widget.
 */
class OrderSelectionButton;
}

/**
 * @class OrderSelectionButton
 * @brief Widget representing a order selection button.
 *
 * The OrderSelectionButton widget displays a button with a order number.
 * When the button is clicked, it emits a signal to notify the system that
 * the order has been selected.
 */
class OrderSelectionButton : public QWidget {
  Q_OBJECT
  
private:
  Ui::OrderSelectionButton* ui = nullptr; ///< Pointer to the UI elements.
  const size_t orderNumber = 0;           ///< The order number displayed on the button.
  
public:
  /**
   * @brief Constructs a OrderSelectionButton widget.
   *
   * Initializes the widget with the provided order number and sets up the UI.
   *
   * @param parent Pointer to the parent widget.
   * @param orderNumber The number to display on the order selection button.
   */
  explicit OrderSelectionButton(QWidget *parent = nullptr
      , const size_t orderNumber = 0);
  
  /**
   * @brief Destructor.
   *
   * Cleans up the UI resources.
   */
  ~OrderSelectionButton();
  
signals:
  /**
   * @brief Emitted when the order selection button is clicked.
   */
  void on_OrderSelectionButton_clicked();
  
private slots:
  /**
   * @brief Slot called when the internal button is clicked.
   *
   * Emits the on_OrderSelectionButton_clicked signal.
   */
  void on_button_clicked();
};

#endif // RECEIPTSELECTIONBUTTON_H
