#ifndef RECEIPTSELECTIONBUTTON_H
#define RECEIPTSELECTIONBUTTON_H

#include <QWidget>

namespace Ui {
/**
 * @brief UI class for ReceiptSelectionButton.
 *
 * This class is generated by Qt Designer and contains the UI components for the
 * ReceiptSelectionButton widget.
 */
class ReceiptSelectionButton;
}

/**
 * @class ReceiptSelectionButton
 * @brief Widget representing a receipt selection button.
 *
 * The ReceiptSelectionButton widget displays a button with a receipt number.
 * When the button is clicked, it emits a signal to notify the system that
 * the receipt has been selected.
 */
class ReceiptSelectionButton : public QWidget {
  Q_OBJECT
  
private:
  Ui::ReceiptSelectionButton* ui = nullptr; ///< Pointer to the UI elements.
  const size_t receiptNumber = 0;           ///< The receipt number displayed on the button.
  
public:
  /**
   * @brief Constructs a ReceiptSelectionButton widget.
   *
   * Initializes the widget with the provided receipt number and sets up the UI.
   *
   * @param parent Pointer to the parent widget.
   * @param receiptNumber The number to display on the receipt selection button.
   */
  explicit ReceiptSelectionButton(QWidget *parent = nullptr
      , const size_t receiptNumber = 0);
  
  /**
   * @brief Destructor.
   *
   * Cleans up the UI resources.
   */
  ~ReceiptSelectionButton();
  
signals:
  /**
   * @brief Emitted when the receipt selection button is clicked.
   */
  void on_ReceiptSelectionButton_clicked();
  
private slots:
  /**
   * @brief Slot called when the internal button is clicked.
   *
   * Emits the on_ReceiptSelectionButton_clicked signal.
   */
  void on_button_clicked();
};

#endif // RECEIPTSELECTIONBUTTON_H
